import type { Judge } from "@/types/judges";

export const JUDGES: Judge[] = [
  {
    id: "judge-fact",
    nameKo: "김팩트",
    nameEn: "Mr. Fact",
    persona: "데이터 기반 냉철한 투자자. 숫자와 근거를 본다.",
    defaultExpression: "neutral",
    accentVar: "var(--judge-fact-accent)",
    triggers: [
      {
        metric: "empty_phrases_count",
        op: ">=",
        value: 1,
        expression: "frown",
        comment: "근거 없는 단정은 위험합니다.",
        priority: 8,
      },
      {
        metric: "core_message_clarity",
        op: ">=",
        value: 80,
        expression: "nod",
        comment: "메시지가 명확하군요.",
        priority: 5,
      },
      {
        metric: "argument_evidence_balance",
        op: "<",
        value: 40,
        expression: "doubt",
        comment: "근거가 부족합니다.",
        priority: 7,
      },
    ],
  },
  {
    id: "judge-connect",
    nameKo: "이공감",
    nameEn: "Ms. Connect",
    persona: "태도와 진정성을 보는 창업가 출신 투자자.",
    defaultExpression: "neutral",
    accentVar: "var(--judge-connect-accent)",
    triggers: [
      {
        metric: "eye_contact_ratio",
        op: "<",
        value: 40,
        expression: "frown",
        comment: "눈을 봐주세요.",
        priority: 8,
      },
      {
        metric: "eye_contact_ratio",
        op: ">=",
        value: 70,
        expression: "smile",
        comment: "좋은 아이컨택입니다.",
        priority: 5,
      },
      {
        metric: "body_sway",
        op: ">",
        value: 70,
        expression: "doubt",
        comment: "긴장이 보이네요.",
        priority: 6,
      },
      {
        metric: "smile_naturalness",
        op: ">=",
        value: 60,
        expression: "smile",
        comment: "자신감이 느껴집니다.",
        priority: 4,
      },
    ],
  },
  {
    id: "judge-critical",
    nameKo: "박독설",
    nameEn: "Dr. Critical",
    persona: "디테일에 강한 독설가 전문가. 약점을 짚는다.",
    defaultExpression: "neutral",
    accentVar: "var(--judge-critical-accent)",
    triggers: [
      {
        metric: "filler_count_per_min",
        op: ">=",
        value: 8,
        expression: "bored",
        comment: "추임새를 줄이세요.",
        priority: 7,
      },
      {
        metric: "pitch_stability",
        op: "<",
        value: 40,
        expression: "doubt",
        comment: "목소리가 떨립니다.",
        priority: 8,
      },
      {
        metric: "pace_cpm",
        op: ">",
        value: 380,
        expression: "surprised",
        comment: "너무 빠릅니다.",
        priority: 6,
      },
      {
        metric: "pace_cpm",
        op: "<",
        value: 220,
        expression: "bored",
        comment: "너무 느립니다.",
        priority: 5,
      },
    ],
  },
];
